server:
  port: 0


  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}-${random.int}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentdb_vehicle?createDatabaseIfNotExist=true
    username: root
    password: root@123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none 

