#server:
 #port: 9191

# here by adding port as 0 , when multiple instances are up from this service those instances will be picked a random port number.
server:
  port: 0

  #Below properties will enable this service to try for register with an eureka server.
  #Below instance properties will generate dynamic ids for each instances of this service(Then eureka server can uniquely identify each instance).

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}-${random.int}







spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentdb_customer?createDatabaseIfNotExist=true
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  zipkin:
    base-url: http://127.0.0.1:9411/
