server:
  port: 9193
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentdb_rent?createDatabaseIfNotExist=true
    username: root
    password: root@123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  

