server:
  port: 0



  #Below properties will enable this service to try for register with an eureka server.
  #Below instance properties will generate dynamic ids for each instances of this service.

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
#  instance:
#    instance-id: ${spring.application.name}-${random.int}







spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentdb_rent?createDatabaseIfNotExist=true
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  zipkin:
    base-url: http://127.0.0.1:9411/